"""Add indexes to articles

Revision ID: 3b90b6af7cb0
Revises: 9eed8d0ddcae
Create Date: 2026-06-04 08:09:58.412946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b90b6af7cb0'
down_revision: Union[str, None] = '9eed8d0ddcae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_articles_category'), 'articles', ['category'], unique=False)
    op.create_index(op.f('ix_articles_is_duplicate'), 'articles', ['is_duplicate'], unique=False)
    op.create_index(op.f('ix_articles_language'), 'articles', ['language'], unique=False)
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_language'), table_name='articles')
    op.drop_index(op.f('ix_articles_is_duplicate'), table_name='articles')
    op.drop_index(op.f('ix_articles_category'), table_name='articles')
    # ### end Alembic commands ###
